This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file ./smsf.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file smsf.acn....done (580 entries accepted, 0 rejected).
Sorting entries........done (6172 comparisons).
Generating output file smsf.acr....done (212 lines written, 0 warnings).
Output written in smsf.acr.
Transcript written in smsf.alg.
